apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-buckets-usage-exporter
  labels:
    app.kubernetes.io/name: prometheus-buckets-usage-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-buckets-usage-exporter
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 30s
  jobLabel: prometheus-buckets-usage-exporter
  namespaceSelector:
    matchNames:
      - openshift-storage
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-buckets-usage-exporter

